# Generated by Django 4.0 on 2023-05-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='name',
            new_name='point1',
        ),
    ]
