# Generated by Django 4.0 on 2023-05-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songo', '0003_presence_tour_points_point10_points_point11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='nom',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
